export interface Recipe {
  strIngredient10: null | string;
  strIngredient11: null | string;
  strMeasure20: null | string;
  strMeasure13: number | null | string;
  strMeasure6: number | null | string;
  strIngredient20: null | string;
  strIngredient13: null | string;
  strIngredient2: string;
  strIngredient1: string;
  strMeasure17: number | null | string;
  strTags: null | string;
  strIngredient15: null | string;
  strIngredient4: string;
  strIngredient5: null | string;
  strIngredient12: null | string;
  strIngredient6: null | string;
  strIngredient14: null | string;
  strIngredient7: null | string;
  strIngredient17: null | string;
  strMeasure7: number | null | string;
  strIngredient8: null | string;
  strIngredient9: null | string;
  strIngredient16: null | string;
  strIngredient19: null | string;
  strIngredient3: string;
  strIngredient18: null | string;
  strArea: string;
  strMealThumb: string;
  strCreativeCommonsConfirmed: null;
  strMeasure10: number | null | string;
  strMeasure14: number | null | string;
  strMeasure8: number | null | string;
  strMeal: string;
  strImageSource: null;
  strMeasure18: null | string;
  strSource: null | string;
  strMeasure1: number | string;
  strInstructions: string;
  idMeal: number;
  strMeasure9: number | null | string;
  strMeasure2: number | string;
  dateModified: null;
  strMeasure11: number | null | string;
  strMeasure15: number | null | string;
  strMeasure19: null | string;
  strMeasure3: number | string;
  strYoutube: string;
  strCategory: string;
  strMeasure4: number | string;
  strMeasure12: number | null | string;
  strMeasure16: number | null | string;
  strDrinkAlternate: null;
  strMeasure5: number | null | string;
}
